[project]
name = "http-server-threaded"
entry = "http-server-threaded.slop"

[build]
include = ["../../lib/std/thread", "/home/jcadam/code/slop/examples/http-server-threaded"]

[build.link]
libraries = ["pthread"]
